[package]
name = "shellus-ultimatus"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.5.4"
tokio = { version = "1.18.0", features = ["full"] }
serde = "1.0.136"